name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: python3 setup.py py2app  
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Cont
