name: Test

on:
  push:
    branches:
      - fix-build

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: dir
      run: |
#        Get-ChildItem -Path D:\ -Filter signtool.exe -Recurse -ErrorAction SilentlyContinue -Force
#        Get-ChildItem -Path C:\ -Filter signtool.exe -Recurse -ErrorAction SilentlyContinue -Force

        ${env:ProgramFiles(x86)}\Windows Kits\10\App /Certification /Kit\signtool.exe

#        dir '"C:\Program%Files%(x86)\Windows%Kits\10\bin\10.0.17763.0\x86\"'
