name: Test

on:
  push:
    branches:
      - fix-build

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: dir
      run: |
        $command="C:\Program Files `(x86`)\Windows Kits\10\App Certification Kit\signtool.exe"

        iex $command