name: Test

on:
  push:
    branches:
      - fix-build

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: dir
      run: |
        dir "C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/"
